### ISSUE TITLE
Dependabot alerts

### ISSUE THREAD

**Issue by crivasestrada** [pnp/action-cli-login#10]
Hi,
I would like to make a request about vulnerabilities detect in the security scan.
I have clone this repository and I haved passed a security scan. The Dependabot alerts show 3 vulnerabilities related to dependencies version included in the package-lock.json:

- path-parse version 1.0.6 --> fixed vulnerability in version 1.0.7 or later
- @actions/core version 1.2.1-->fixed vulnerability in version 1.2.6 or later
- minimist version 0.0.8 --> fixed vulnerability in version 0.2.1 or later

Please, I would like to know if there is any plan to upgrade these dependencies version in orden to eliminate le vulnerabilities.

Thanks in advanced

**Comment by waldekmastykarz** [comment]
Yes, we'll definitely upgrade the actions. Thank you for bearing with us.

**Comment by garrytrinder** [comment]
Below is the output of executing `npm outdated` 

<img width="630" alt="image" src="https://user-images.githubusercontent.com/11563347/140589177-c2de856c-3e04-4e3f-8f04-134e40940222.png">

It is worth noting that both `tslint` and `@zeit/ncc` have both been deprecated and are no longer being actively maintained, therefore we should look to replace with with `eslint` and `@vercel/ncc` respectively.

As we have just moved `CLI for Microsoft 365` to use `node@16` recently, I think it makes sense to bump the types to v16 and also increase the `typescript` version to the latest.

I have an updated branch https://github.com/garrytrinder/action-cli-login/tree/dependencies which reflects the updated dependencies whilst removing the deprecated packages. 

@waldekmastykarz as there are no breaking changes here, do you agree that we should just increment the version to `2.0.1`?

**Comment by waldekmastykarz** [comment]
Agreed 👍

**Comment by garrytrinder** [comment]
PR has been merged, unfortunately we need to accept the GitHub Marketplace Agreement before we can release v2.0.1 to the marketplace, as this is an pnp org decision/action I am unable to accept the agreement myself, so re-opening this issue until that is resolved and we can complete with a v2.0.1 release.

**Comment by garrytrinder** [comment]
Thank you for raising this issue @crivasestrada 👍🏻 

We have just released a new version, v2.0.1, that addresses these vulnerabilities.
