### ISSUE TITLE
Add 'CLI_VERSION' option to allow users to specify a specific version installed and used

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/action-cli-login#19]
Add 'CLI_VERSION' option to allow users to specify a specific version installed and used

As discussed in issue #18. 

## Description
The version of the CLI that's installed is the published version. But there may be situations where you want the latest beta release to be installed. Like when a new feature or bugfix is rolling out.

**Comment by michaelmaillot** [comment]
Thanks for the suggestion, I'll handle it if that's ok for you 🙂

**Comment by martinlingstuyl** [comment]
I've got enough other things I want to do as well, so that's okay 😝

**Comment by michaelmaillot** [comment]
Can you assign it to me?

Would you mind to rename the option `USE_NEXT` in the issue title, in order to be consistent with all other options (et reflect GitHub Actions naming convention)?

**Comment by martinlingstuyl** [comment]
> Can you assign it to me?

Sure 😂 totally forgot.

> Would you mind to rename the option `USE_NEXT` in the issue title, in order to be consistent with all other options (et reflect GitHub Actions naming convention)?

Of course!

**Comment by michaelmaillot** [comment]
Ready for review 🙂

**Comment by pkskelly** [comment]
Looking forward to this one!  Thanks for getting it implemented so quickly @michaelmaillot!

**Comment by garrytrinder** [comment]
Nice suggestion @martinlingstuyl 

I'm wondering, rather than just a flag to install the current beta version, we could expose an optional parameter `CLI_VERSION` that accepts a `tag` or `version`, and would default to `latest` if a value is not provided.

This approach would enable you use use any version currently in npm, giving the user of the action full control over the version they want to use, either a tag or specific version.

The value would simply be added to the end of the npm install command.

## Tags
```
npm i @pnp/cli-microsoft365@latest
npm i @pnp/cli-microsoft365@next
npm i @pnp/cli-microsoft365@six
```
## Versions
```
npm i @pnp/cli-microsoft365@5.4.0
npm i @pnp/cli-microsoft365@5.5.0-beta.ae1ef3e
```

**Comment by pkskelly** [comment]
@garrytrinder I would prefer your CLI_VERSION suggestion since this would allow pinning a version in a CI/CD process to ensure predictable version usage and intentional upgrades.

**Comment by martinlingstuyl** [comment]
> I'm wondering, rather than just a flag to install the current beta version, we could expose an optional parameter CLI_VERSION that accepts a tag

Agreed, that's much better! Should have thought of it. @michaelmaillot already submitted a PR though. Would you mind changing it @michaelmaillot?

**Comment by michaelmaillot** [comment]
Also agreed with you, should also have thought about it!

I'll update it accordingly.

Also, would you mind updating the issue title @martinlingstuyl to keep consistency?

**Comment by waldekmastykarz** [comment]
@pkskelly I believe you could choose yourself whether you want to pass a tag or a specific version. Basically, whatever is supported by npm, we'd support as well.

**Comment by pkskelly** [comment]
Thanks @waldekmastykarz.  I think @garrytrinder  was suggesting some refactoring as well for internal reasons. Looking forward to when this is completed! Thanks for everyone's work!

**Comment by pkskelly** [comment]
@garrytrinder - tested the updates this morning and everything is working perfectly.  Complex password on my production account now working with using CLI_VERSION = 'next' in my config.  Thanks so much for the update! And thanks @martinlingstuyl , @michaelmaillot and @waldekmastykarz too!

**Comment by martinlingstuyl** [comment]
Awesome @pkskelly!

**Comment by garrytrinder** [comment]
Great to hear @pkskelly 🚀

Thank you for testing this and confirming that all is well, it is much appreciated ❤️
