### ISSUE TITLE
`node18` is not a valid `run.uses` value

### ISSUE THREAD

**Issue by garrytrinder** [pnp/action-cli-login#28]
In `actions.yml` we reference `node18`, but this breaks the `yaml` schema validation.

https://github.com/pnp/action-cli-login/blob/dda9848b627844079f147a5291963140eac9c28b/action.yml#L26C18-L26C18

![image](https://github.com/pnp/action-cli-login/assets/11563347/8e7e8c47-2cf3-47ea-8b41-715c4897b261)

`runs.uses` should be either `node12` or `node16`.

![image](https://github.com/pnp/action-cli-login/assets/11563347/eef0a265-b0b2-41bd-88e0-458e1e7fc516)

Schema [https://json.schemastore.org/github-action.json](https://json.schemastore.org/github-action.json)

/cc @milanholemans apologies, I missed this in the review 😞

**Comment by milanholemans** [comment]
That's a shame. Is there no way for us to let it run using Node18? Since the CLI requires Node18 as a minimum, it doesn't seem logical to leave this on Node16.

Can't we use [actions/setup-node@v3](https://github.com/actions/setup-node) to setup our own Node version?

**Comment by garrytrinder** [comment]
> Since the CLI requires Node18 as a minimum, it doesn't seem logical to leave this on Node16.

IIRC, you can run the CLI on `node@16` just fine, but `node@18` is required for development of the CLI.

> Can't we use [actions/setup-node@v3](https://github.com/actions/setup-node) to setup our own Node version?

I don't think this is relevant in this context. The `action.yml` represents the metadata of the action, it is not a GitHub workflow.

**Comment by milanholemans** [comment]
> IIRC, you can run the CLI on `node@16` just fine, but `node@18` is required for development of the CLI.

Not only for development but also to use the CLI. It's possible that it works on Node16, but there is no guarantee since we don't test anything on Node16 anymore.

https://pnp.github.io/cli-microsoft365/user-guide/installing-cli#prerequisites

**Comment by garrytrinder** [comment]
Thanks for clarifying.

As you can see I’ve reverted the change to resolve the validation error.

If using node@16 becomes an issue, then we should maybe look to move to Docker style actions where we can define the runtime environment to our needs.

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-a-dockerfile

**Comment by garrytrinder** [comment]
`node12` is going away and the only option will be `node16`

https://github.blog/changelog/2023-07-17-github-actions-removal-of-node12-from-the-actions-runner/

Also, we should track this issue https://github.com/actions/runner/issues/2619 which is asking for latest node support.

**Comment by milanholemans** [comment]
https://github.com/orgs/community/discussions/53217#discussioncomment-6227341

This might work.
