### ISSUE TITLE
@pnp/office365-cli update check failed

### ISSUE THREAD

**Issue by garrytrinder** [pnp/action-cli-login#4]
When using the action in a GitHub workflow, the message `@pnp/office365-cli update check failed` is displayed twice in the build step output.

![image](https://user-images.githubusercontent.com/11563347/72741195-0cdefa80-3b9f-11ea-96e8-4783f7a476dc.png)

**Comment by VelinGeorgiev** [comment]
Update: This is happening for just `ubuntu` agents.

**Comment by waldekmastykarz** [comment]
Could it be because CLI is ran multiple times, its state is not persisted and on each run CLI tries to check for the latest version? Still, if it's an issue and checking for versions is not an option, we should consider extending the CLI to disable version check in such cases.

**Comment by michaelmaillot** [comment]
Is this bug still occur? When working on the v2.1.0 of the action, I didn't get this update check message at all.

Did you @garrytrinder?

**Comment by garrytrinder** [comment]
Thanks for the reminder @michaelmaillot 

I'll see if I can replicate.

**Comment by garrytrinder** [comment]
Looks like this is no longer an issue.

![image](https://user-images.githubusercontent.com/11563347/178842655-70857b96-f122-4ede-a96a-d3e7889fa834.png)

Closing
