### ISSUE TITLE
action-cli-login doesn't work as described in the read.me for v2.0.0

### ISSUE THREAD

**Issue by ggalipeau-takeda** [pnp/action-cli-login#8]
The read.me on how to use the action-cli-login still says to use the admin_username and admin_password like so:
     - name: Login to tenant
      uses: pnp/action-cli-login@v2.0.0
      with:
        ADMIN_USERNAME:  ${{ secrets.adminUsername }}
        ADMIN_PASSWORD:  ${{ secrets.adminPassword }}

If I run this I get an error saying "Login to the tenant failed" even though I know the username and password is right.

I verified the credentials are correct by switching back to v1.0.0 and it works perfectly.

After talking to my team, they mentioned there might be a different way to login now with v.2.0.0 of the CLI for Microsoft 365.

So, I think there might be an issue with the documentation on this site of how to login in with v2.0.0. Can you let me know how to login with the v2.0.0 of this?

**Comment by waldekmastykarz** [comment]
Sorry to hear you're running into trouble. Next to the error message you mentioned, you should also see the actual error that triggered the failure. Is there any more information that you could share with us to help us understand what's wrong?

**Comment by ggalipeau-takeda** [comment]
The next line is Error: The process '/usr/local/bin/m365' failed with exit code 1. Here is a screenshot:
![CLIError](https://user-images.githubusercontent.com/78168613/117045993-277aab80-acde-11eb-9364-5115e0ec09fe.png)

FYI - I know it looks like it might just be a simple credential error. So, we did change the version from 2.0.0 to 1.0.0 and it worked. I only get this when the version is 2.0.0

**Comment by waldekmastykarz** [comment]
I think the hint is in line 11: invalid_grant AADSTS50126. One of the common reasons is that the used account uses federated authentication which isn't supported. Could that be the case for you? Have you tried installing CLI locally and logging in using the same credentials to verify that it's working there as expected?

**Comment by ggalipeau-takeda** [comment]
Unfortunately, I can't do that. I work in a large organization. My personal account is federated, 2-factor authentication. For GitHub, there are organizational secrets. That account is supposedly a cloud/onmicrosoft.com account. I don't actually know that account (i.e.: I can't see the username/password because it's an organizational secret). But, I am 99% sure it is an onmicrosoft.com account because I had to add it to my site for everything to work.

Too bad - I can't verify this exactly. Your suggestion would have been exactly what I would have done if I could.

Question - what change between version 1.0.0 and 2.0.0 in the Microsoft CLI? The weird thing is this all works with version 1.0.0 and doesn't with 2.0.0. Was there any changes to authentication between those versions?

Thanks!

**Comment by waldekmastykarz** [comment]
The version 2 of the action uses the latest version of CLI for Microsoft 365 which is v3. Recently we replaced ADAL.js with MSAL.js which is the only relevant change to the auth. By itself though, it shouldn't have any impact on the password auth process. Is there another account that you could use with CLI v3 to see if you can login locally?

**Comment by ggalipeau-takeda** [comment]
Unfortunately, I do not have another account. My personal account is 2 factor/federated. And, requesting an account would take forever here. I am just going to stick with 1.0.0 of the product for now.

Something must have changed in the ADAL vs MSAL to cause this. I can literally change the 1 to a 2 and it stops working. Very weird. 

Regardless, the 1.0.0 is working and I'll stick with that for now and deal with this at a later time.

**Comment by waldekmastykarz** [comment]
Sorry I don't have a better answer for you.
